### ISSUE TITLE
what's error?

### ISSUE THREAD

**Issue by Ruilkyu** [pkuCactus/BDCN#18]
python train.py

FileNotFoundError: [Errno 2] No such file or directory: 'path_to/bsds500/HED-BSDS/train_pair.lst'

**Comment by huberthomas** [comment]
As far as I can remember you do have to download the training dataset from here: http://vcl.ucsd.edu/hed/HED-BSDS.tar (see https://github.com/s9xie/hed for more information)
If you extract it you will find the train_pair.lst file which contains file correspondences between ground truth and rgb data.
After that you do have to adapt the config file, e.g. see https://github.com/pkuCactus/BDCN/blob/master/cfg.py#L33 for the default setting.

**Comment by Ruilkyu** [comment]
Thank you very much!
