### ISSUE TITLE
Training Memory Consumption

### ISSUE THREAD

**Issue by huberthomas** [pkuCactus/BDCN#20]
Is it possible to train with a Nvidia GTX 1080 Ti with 11GB GDDR RAM? I always run out of memory but installed your recommended software via conda. Without CUDA support my system has peaks around 20GB RAM and I don't know if this is also too much. If you use your graphic card for learning can you tell me your configuration? 

My settings: Ubuntu 16.04 LTS, Nvidia Driver: 418.67, Cuda: 9.2

Big thanks in advance!

**Comment by jannctu** [comment]
hi @huberthomas 

I run on the similar environment as yours and it's work fine. 

Ubuntu 16.04.5 LTS
Nvidia GTX 1080 Ti with 11GB Memory
NVIDIA Driver 410.48   
CUDA 9.0

**Comment by huberthomas** [comment]
Thank you very much, I played around with my configuration and found a setting that is working:

Ubuntu 16.04 LTS, Nvidia: 418.67, cuda: 9.2, cudnn: 7.6
conda install ninja pyyaml mkl mkl-include setuptools cmake cffi typing torchvision scipy numpy pillow opencv matplotlib pytorch=0.4.1 cuda92 python=2.7 -c pytorch
