### ISSUE TITLE
links to datasets

### ISSUE THREAD

**Issue by molefeskymleya** [pkuCactus/BDCN#26]
hello there! :) I am in love with your work! I got some of the datasets from [http://mftp.mmcheng.net/liuyun/rcf/data/ ](url) but unfortunately... I still seem to be getting data related errors for example... 
'''
`Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/BDCN-master/datasets/dataset.py", line 69, in __getitem__
    img = load_image_with_cache(img_file, self.cache)
  File "/BDCN-master/datasets/dataset.py", line 34, in load_image_with_cache
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path_to/bsds500/HED-BSDS/train/aug_data_scale_1.5/247.5_1_0/144067.png'`

'''
My aug_data_scale_1.5 does not have the file 247.5_1_0. I am not sure where I am going wrong.
If possible, may you please help me with links to the actual datasets you used in the experiments. This would be really helpful.

**Comment by pkuCactus** [comment]
You could download data from the http://mftp.mmcheng.net/liuyun/rcf/data/HED-BSDS.tar.gz, which the data preprocessed by Dr, Liu and thanks he for the data provided. And then change the /path_to to you real directory which store the data.
