### ISSUE TITLE
Cannot find the caffe model

### ISSUE THREAD

**Issue by tristanclare94** [pkuCactus/BDCN#34]
Hi,

I cannot find the caffe model in the model zoo, is it available elsewhere?

Thanks in advance,
Tristan

**Comment by pkuCactus** [comment]
Hi,

You can got the model from http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel,  or the link https://github.com/BVLC/caffe/wiki/Model-Zoo#models-used-by-the-vgg-team-in-ilsvrc-2014
and we also provided the converted model here https://pan.baidu.com/s/10Tgjs7FiAYWjVyVgvEM0mA.

**Comment by tristanclare94** [comment]
Thanks!
