### ISSUE TITLE
Why batch_size =1 ?

### ISSUE THREAD

**Issue by Dreamerswile** [pkuCactus/BDCN#36]
I would like to ask why batch_size=1?I believe this may be the best result of tuning parameters, Is it because the model has an image with a gray background?

**Comment by pkuCactus** [comment]
We do not crop the train data to fixed size when training, the size are different that can't batch to together, so we forward one image each iteration. Here, we adopt the itersize=10 which analogs to batchsize=10, ie, forward 10 times and then update the weights.

**Comment by Dreamerswile** [comment]
I couldn't agree with you more.But why did you choose this way instead of resizing the image.Cropping the image size also increases the batchsize and reduces training time.Is the method you used the best result of the experiment?Thank you very much for your answer
