### ISSUE TITLE
Multicue groundtruth file for edge detection result evaluation 

### ISSUE THREAD

**Issue by rrryan2016** [pkuCactus/BDCN#40]
Hello, thanks for your kind sharing and great work. 

I currently intend to evaluate my edge detection model's performance on Multicue dataset, but I could not obtain the groundtruth file of it, could you please give me any advice on it?

**Comment by pkuCactus** [comment]
I upload the ground truth below which includes image format and mat format.
[gt.zip](https://github.com/pkuCactus/BDCN/files/6061832/gt.zip)

**Comment by rrryan2016** [comment]
Thanks SOOOO much !

**Comment by rrryan2016** [comment]
> I upload the ground truth below which includes image format and mat format.
> [gt.zip](https://github.com/pkuCactus/BDCN/files/6061832/gt.zip)

Sorry for the disturbance again, I noticed the zipped files you provided only contain groundtruth file of 20 images, I guess it may be a random split in your experiment. 

For the reason that, for multicue, it is better to train in 3 random splits, could you please offer me the groundtruth files of all 100 images if it is convenience to you?

**Comment by pkuCactus** [comment]
link：https://pan.baidu.com/s/1Yx9CYllZtYtu5k-FahzpbA 
code：k817 
I have stored the gt on the above link, you can download it from it.

**Comment by rrryan2016** [comment]
> link：https://pan.baidu.com/s/1Yx9CYllZtYtu5k-FahzpbA
> code：k817
> I have stored the gt on the above link, you can download it from it.

Cheers man! That's what I actually need. Thanks for everything.
