### ISSUE TITLE
网络输出的第7,8,9,10维度输出纯灰白图像?(Output pure gray image in dimension 7,8,9,10 of network output?)

### ISSUE THREAD

**Issue by better-space** [pkuCactus/BDCN#42]
这个问题困扰了很久,检查损失计算应该也没问题.我对于下载的核心部分代码没有做任何修改,但是我每次对训练后的模型做测试的时候,一张图片的第7,8,9,10输出尺度都是灰白图像,好像没有起到训练效果.请问有人遇到同样的问题吗?这会是什么原因呢?你们是如何解决的?

This problem has been bothering me for a long time, and it should be OK to check the loss calculation. I didn't make any changes to the core part of the code downloaded, but every time I test the model after training, the 7th, 8th, 9th and 10th output scales of an image are gray, It doesn't seem to have any training effect. Does anyone encounter the same problem? What's the reason? How do you solve it?

**Comment by ForawardStar** [comment]
@better-space 我遇到过这个问题，原因是没有加载预训练的VGG16作为模型的初始化，他们给的代码里默认是随机初始化，需要我们自己设计预训练VGG16的路径
