### ISSUE TITLE
The reproduction result is poor

### ISSUE THREAD

**Issue by liuxingyu123** [pkuCactus/BDCN#55]
hello，My training results are poor,ois:0.749,ods:0.759,ap:0.525, and the test plot is abnormal. Do you know why？
![image](https://user-images.githubusercontent.com/59238693/191260759-b6678d2a-4da8-4900-8dc0-c59f086c0996.png)

**Comment by CookiC** [comment]
@liuxingyu123 你最后复现成功了吗？
