### ISSUE TITLE
The maximum tolerance

### ISSUE THREAD

**Issue by xavysp** [pkuCactus/BDCN#6]
Dear @pkuCactus,
 thanks for sharing the code and the paper. I have a naive question :( (I think), in page 5 of your paper: "The maximum tolerance allowed for correct matches between edge predictions and groundtruth annotations is set to **0.0075** for BSDS500 and Multicue dataset, and is set to **0.011** for NYUDv2 dataset". Could you please explain to me about it, and tell me where are you doing this?

Thanks in advance

**Comment by pkuCactus** [comment]
Hi，
Thanks for your interest in our work. The tolerance is set in the evaluation code provided by _Contour
detection and hierarchical image segmentation_,  where you can find the BSDS500 data and evaluation code.
